name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Maven Build
      run: mvn clean verify

    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=spring-mvc-app \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: docker build -t spring-mvc-app:latest .Docker-files/app/.

    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: spring-mvc-app:latest
        scanners: vuln
        severity: HIGH,CRITICAL
        exit-code: 1
        timeout: 15m

    - name: Tag & Push Image to ECR
      run: |
        docker tag spring-mvc-app:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

        docker push \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
